# This is for development and testing purposes only. It is not intended for production use.
services:
  app:
    build:
      context: .
      dockerfile_inline: |
        FROM ruby:3.3.0
        RUn echo 'IRB.conf[:USE_AUTO_INDENT] = false' >> ~/.irbrc
        WORKDIR /rails
        RUN bundle config set --local path /bundle
    tty: true
    stdin_open: true
    volumes:
      - .:/rails:cached
      - ./tmp/bundle:/bundle
    command: bash -c 'rm -f tmp/pids/server.pid; ./bin/dev'
    ports:
      - '3000:3000'
    environment:
      CHROME_URL: http://chrome:3333
    depends_on:
      - chrome

  chrome:
    image: browserless/chrome:1-chrome-stable
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
      CONNECTION_TIMEOUT: 600000
