name: CI

on: push

env:
  BUNDLE_STORE_PATH: ./tmp/bundle

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ env.BUNDLE_STORE_PATH }}
          key: gems-${{ hashFiles('Gemfile.lock') }}

      - name: Build
        run: docker compose build

      - name: Lint
        run: docker compose run app bin/rubocop

      - name: Set up for test
        run: |
          docker compose run app bin/setup --skip-server
          docker compose up -d

      - name: Test
        run: docker compose exec -T app bin/rails test:all

      - name: Set owner of the file to cache
        run: sudo chown -R $(whoami) ${{ env.BUNDLE_STORE_PATH }}
