name: CI

on: push

env:
  BUNDLE_STORE_PATH: ./tmp/bundle

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache
        id: cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ env.BUNDLE_STORE_PATH }}
          key: gems-${{ hashFiles('Gemfile.lock') }}

      - name: Build and prepare
        run: |
          docker compose build
          docker compose run app bin/setup --skip-server

      - name: Lint
        run: docker compose run app bin/rubocop

      - name: Test
        run: docker compose run -T app bin/rails test:all

      - name: Set owner of the file to cache
        run: sudo chown -R $(whoami) ${{ env.BUNDLE_STORE_PATH }}
